### ISSUE TITLE
Babel parser fails at deeper queries

### ISSUE THREAD

**Issue by gitcatrat** [grafoojs/grafoo#90] opened 2020-08-20 10:24 UTC
Babel parser fails on deep(ish) queries.

```graphql
  query SearchAds($first: int $bounds: Bounds) {
    # babel parser stops at this level, i.e doesn't go deeper than "search" and because it
    # doesnt have arguments, args is [] and changing query variables doesn't refetch the query
    search {
      people(first: $first bounds: $bounds) {
        edges {
          node {
            id
            name
          }
        }
      }
      cars(first: $first bounds: $bounds) {
        edges {
          node {
            id
            name
          }
        }
      }
    }
  }
```

**Comment by gitcatrat** [comment] 2020-08-20 10:26
Suggested solution: take arguments from query variable definitions, not from the arguments fields.

**Comment by gitcatrat** [comment] 2020-08-20 10:45
Possible solution: iterate over all `search` children as well and gather all the arguments into args array.

**Comment by malbernaz** [comment] 2020-09-24 23:05
I'll investigate the issue @gitcatrat, but if you fell you have a solution for it, I'd have no problems to review a pr.

**Comment by malbernaz** [comment] 2020-12-09 17:52
@gitcatrat do you have a repo where I can test this, or at least give me a deeper explanation of the problem?

**Comment by malbernaz** [comment] 2021-10-05 23:58
I could not reproduce this by any means. The query seems a bit odd. Maybe the arguments should be on search rather then car and people. If a query is not written correctly babel plugin will fail. Either way I closing this.

**Closed by malbernaz** 2021-10-05 23:58 UTC
